### ISSUE TITLE
Breaks when I nest files more than one level deep

### ISSUE THREAD

**Issue by JDuchniewicz** [Guergeiro/clean-path.vim#2]
Hi!
Good job on the plugin! I really do not want to specify all the extensions to `path`  for all languages I am using so I decided to use your plugin.

So far so good, until I decided to make some reordering in my project: instead of `src`/`include` split I decided to go for `src` and subfolders -> put the source files inside them. This broke the plugin until I fixed the `getdirectories()` function to take `-maxdepth 2` as argument.

This probably could be fixed so that user can specify the recursion depth or provide some more sensible value for it.

**Comment by Guergeiro** [comment]
Hello @JDuchniewicz I've made a PR that might solve your issue. Can you test the branch and then report back?
